/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GameEscrow {
  export type MatchStruct = {
    player1: AddressLike;
    player2: AddressLike;
    betAmount: BigNumberish;
    isActive: boolean;
    winner: AddressLike;
  };

  export type MatchStructOutput = [
    player1: string,
    player2: string,
    betAmount: bigint,
    isActive: boolean,
    winner: string
  ] & {
    player1: string;
    player2: string;
    betAmount: bigint;
    isActive: boolean;
    winner: string;
  };
}

export interface GameEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMatch"
      | "getMatches"
      | "joinMatch"
      | "matchCount"
      | "matches"
      | "owner"
      | "settleMatch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchCreated" | "MatchSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createMatch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "joinMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "settleMatch",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleMatch",
    data: BytesLike
  ): Result;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    player1: AddressLike,
    player2: AddressLike,
    betAmount: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    player1: string,
    player2: string,
    betAmount: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    player1: string;
    player2: string;
    betAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchSettledEvent {
  export type InputTuple = [matchId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [matchId: bigint, winner: string];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): GameEscrow;
  waitForDeployment(): Promise<this>;

  interface: GameEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMatch: TypedContractMethod<[_player2: AddressLike], [void], "payable">;

  getMatches: TypedContractMethod<[], [GameEscrow.MatchStructOutput[]], "view">;

  joinMatch: TypedContractMethod<[_matchId: BigNumberish], [void], "payable">;

  matchCount: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, string] & {
        player1: string;
        player2: string;
        betAmount: bigint;
        isActive: boolean;
        winner: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  settleMatch: TypedContractMethod<
    [_matchId: BigNumberish, _winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<[_player2: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getMatches"
  ): TypedContractMethod<[], [GameEscrow.MatchStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "joinMatch"
  ): TypedContractMethod<[_matchId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "matchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean, string] & {
        player1: string;
        player2: string;
        betAmount: bigint;
        isActive: boolean;
        winner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settleMatch"
  ): TypedContractMethod<
    [_matchId: BigNumberish, _winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchSettled"
  ): TypedContractEvent<
    MatchSettledEvent.InputTuple,
    MatchSettledEvent.OutputTuple,
    MatchSettledEvent.OutputObject
  >;

  filters: {
    "MatchCreated(uint256,address,address,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchSettled(uint256,address)": TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
    MatchSettled: TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
  };
}
