/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GameEscrow {
  export type MatchStruct = {
    player1: AddressLike;
    player2: AddressLike;
    betAmount: BigNumberish;
    state: BigNumberish;
    winner: AddressLike;
    currentTurn: AddressLike;
    moves: BigNumberish;
    board: BigNumberish[];
  };

  export type MatchStructOutput = [
    player1: string,
    player2: string,
    betAmount: bigint,
    state: bigint,
    winner: string,
    currentTurn: string,
    moves: bigint,
    board: bigint[]
  ] & {
    player1: string;
    player2: string;
    betAmount: bigint;
    state: bigint;
    winner: string;
    currentTurn: string;
    moves: bigint;
    board: bigint[];
  };
}

export interface GameEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BOARD_SIZE"
      | "DEFAULT_ELO"
      | "ELO_DELTA"
      | "createMatch"
      | "getMatch"
      | "getMatches"
      | "getPlayerElo"
      | "getPlayerHistory"
      | "getPlayerMatchIds"
      | "joinMatch"
      | "makeMove"
      | "matchCount"
      | "matches"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EloUpdated"
      | "MatchCreated"
      | "MatchFinished"
      | "MatchJoined"
      | "MatchStarted"
      | "MovePlayed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BOARD_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ELO",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ELO_DELTA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createMatch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatches",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerElo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerMatchIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinMatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeMove",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matches",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "BOARD_SIZE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ELO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ELO_DELTA", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMatches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerElo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerMatchIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinMatch", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeMove", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matches", data: BytesLike): Result;
}

export namespace EloUpdatedEvent {
  export type InputTuple = [player: AddressLike, newElo: BigNumberish];
  export type OutputTuple = [player: string, newElo: bigint];
  export interface OutputObject {
    player: string;
    newElo: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchCreatedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    player1: AddressLike,
    betAmount: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    player1: string,
    betAmount: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    player1: string;
    betAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchFinishedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    winner: AddressLike,
    isDraw: boolean,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    winner: string,
    isDraw: boolean,
    payout: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    winner: string;
    isDraw: boolean;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchJoinedEvent {
  export type InputTuple = [matchId: BigNumberish, player2: AddressLike];
  export type OutputTuple = [matchId: bigint, player2: string];
  export interface OutputObject {
    matchId: bigint;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchStartedEvent {
  export type InputTuple = [matchId: BigNumberish, currentTurn: AddressLike];
  export type OutputTuple = [matchId: bigint, currentTurn: string];
  export interface OutputObject {
    matchId: bigint;
    currentTurn: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MovePlayedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    player: AddressLike,
    position: BigNumberish,
    mark: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    player: string,
    position: bigint,
    mark: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    player: string;
    position: bigint;
    mark: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GameEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): GameEscrow;
  waitForDeployment(): Promise<this>;

  interface: GameEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BOARD_SIZE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ELO: TypedContractMethod<[], [bigint], "view">;

  ELO_DELTA: TypedContractMethod<[], [bigint], "view">;

  createMatch: TypedContractMethod<[], [bigint], "payable">;

  getMatch: TypedContractMethod<
    [matchId: BigNumberish],
    [GameEscrow.MatchStructOutput],
    "view"
  >;

  getMatches: TypedContractMethod<[], [GameEscrow.MatchStructOutput[]], "view">;

  getPlayerElo: TypedContractMethod<[player: AddressLike], [bigint], "view">;

  getPlayerHistory: TypedContractMethod<
    [player: AddressLike],
    [
      [GameEscrow.MatchStructOutput[], bigint[]] & {
        playerMatches: GameEscrow.MatchStructOutput[];
        matchIds: bigint[];
      }
    ],
    "view"
  >;

  getPlayerMatchIds: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  joinMatch: TypedContractMethod<[matchId: BigNumberish], [void], "payable">;

  makeMove: TypedContractMethod<
    [matchId: BigNumberish, position: BigNumberish],
    [void],
    "nonpayable"
  >;

  matchCount: TypedContractMethod<[], [bigint], "view">;

  matches: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string, string, bigint] & {
        player1: string;
        player2: string;
        betAmount: bigint;
        state: bigint;
        winner: string;
        currentTurn: string;
        moves: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BOARD_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ELO"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ELO_DELTA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createMatch"
  ): TypedContractMethod<[], [bigint], "payable">;
  getFunction(
    nameOrSignature: "getMatch"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [GameEscrow.MatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatches"
  ): TypedContractMethod<[], [GameEscrow.MatchStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPlayerElo"
  ): TypedContractMethod<[player: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayerHistory"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [GameEscrow.MatchStructOutput[], bigint[]] & {
        playerMatches: GameEscrow.MatchStructOutput[];
        matchIds: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerMatchIds"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "joinMatch"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "makeMove"
  ): TypedContractMethod<
    [matchId: BigNumberish, position: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "matchCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matches"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, string, string, bigint] & {
        player1: string;
        player2: string;
        betAmount: bigint;
        state: bigint;
        winner: string;
        currentTurn: string;
        moves: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "EloUpdated"
  ): TypedContractEvent<
    EloUpdatedEvent.InputTuple,
    EloUpdatedEvent.OutputTuple,
    EloUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchCreated"
  ): TypedContractEvent<
    MatchCreatedEvent.InputTuple,
    MatchCreatedEvent.OutputTuple,
    MatchCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MatchFinished"
  ): TypedContractEvent<
    MatchFinishedEvent.InputTuple,
    MatchFinishedEvent.OutputTuple,
    MatchFinishedEvent.OutputObject
  >;
  getEvent(
    key: "MatchJoined"
  ): TypedContractEvent<
    MatchJoinedEvent.InputTuple,
    MatchJoinedEvent.OutputTuple,
    MatchJoinedEvent.OutputObject
  >;
  getEvent(
    key: "MatchStarted"
  ): TypedContractEvent<
    MatchStartedEvent.InputTuple,
    MatchStartedEvent.OutputTuple,
    MatchStartedEvent.OutputObject
  >;
  getEvent(
    key: "MovePlayed"
  ): TypedContractEvent<
    MovePlayedEvent.InputTuple,
    MovePlayedEvent.OutputTuple,
    MovePlayedEvent.OutputObject
  >;

  filters: {
    "EloUpdated(address,int256)": TypedContractEvent<
      EloUpdatedEvent.InputTuple,
      EloUpdatedEvent.OutputTuple,
      EloUpdatedEvent.OutputObject
    >;
    EloUpdated: TypedContractEvent<
      EloUpdatedEvent.InputTuple,
      EloUpdatedEvent.OutputTuple,
      EloUpdatedEvent.OutputObject
    >;

    "MatchCreated(uint256,address,uint256)": TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;
    MatchCreated: TypedContractEvent<
      MatchCreatedEvent.InputTuple,
      MatchCreatedEvent.OutputTuple,
      MatchCreatedEvent.OutputObject
    >;

    "MatchFinished(uint256,address,bool,uint256)": TypedContractEvent<
      MatchFinishedEvent.InputTuple,
      MatchFinishedEvent.OutputTuple,
      MatchFinishedEvent.OutputObject
    >;
    MatchFinished: TypedContractEvent<
      MatchFinishedEvent.InputTuple,
      MatchFinishedEvent.OutputTuple,
      MatchFinishedEvent.OutputObject
    >;

    "MatchJoined(uint256,address)": TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;
    MatchJoined: TypedContractEvent<
      MatchJoinedEvent.InputTuple,
      MatchJoinedEvent.OutputTuple,
      MatchJoinedEvent.OutputObject
    >;

    "MatchStarted(uint256,address)": TypedContractEvent<
      MatchStartedEvent.InputTuple,
      MatchStartedEvent.OutputTuple,
      MatchStartedEvent.OutputObject
    >;
    MatchStarted: TypedContractEvent<
      MatchStartedEvent.InputTuple,
      MatchStartedEvent.OutputTuple,
      MatchStartedEvent.OutputObject
    >;

    "MovePlayed(uint256,address,uint8,uint8)": TypedContractEvent<
      MovePlayedEvent.InputTuple,
      MovePlayedEvent.OutputTuple,
      MovePlayedEvent.OutputObject
    >;
    MovePlayed: TypedContractEvent<
      MovePlayedEvent.InputTuple,
      MovePlayedEvent.OutputTuple,
      MovePlayedEvent.OutputObject
    >;
  };
}
