/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace InsuranceEscrow {
  export type PolicyStruct = {
    insurer: AddressLike;
    insured: AddressLike;
    coverageAmount: BigNumberish;
    premiumAmount: BigNumberish;
    durationSeconds: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    location: string;
    windSpeedKmh: BigNumberish;
    state: BigNumberish;
    eventOccurred: boolean;
  };

  export type PolicyStructOutput = [
    insurer: string,
    insured: string,
    coverageAmount: bigint,
    premiumAmount: bigint,
    durationSeconds: bigint,
    startTime: bigint,
    endTime: bigint,
    location: string,
    windSpeedKmh: bigint,
    state: bigint,
    eventOccurred: boolean
  ] & {
    insurer: string;
    insured: string;
    coverageAmount: bigint;
    premiumAmount: bigint;
    durationSeconds: bigint;
    startTime: bigint;
    endTime: bigint;
    location: string;
    windSpeedKmh: bigint;
    state: bigint;
    eventOccurred: boolean;
  };
}

export interface InsuranceEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptPolicy"
      | "cancelOffer"
      | "createPolicyOffer"
      | "finalizeExpiredPolicy"
      | "getPolicies"
      | "getPolicy"
      | "oracle"
      | "owner"
      | "policies"
      | "policyCount"
      | "resolvePolicy"
      | "setOracle"
      | "setVerified"
      | "transferOwnership"
      | "verifiedUsers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OracleUpdated"
      | "OwnershipTransferred"
      | "PolicyAccepted"
      | "PolicyCancelled"
      | "PolicyOffered"
      | "PolicyResolved"
      | "VerifiedUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOffer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicyOffer",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeExpiredPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolvePolicy",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerified",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedUsers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPolicyOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeExpiredPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolvePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedUsers",
    data: BytesLike
  ): Result;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [newOracle: AddressLike];
  export type OutputTuple = [newOracle: string];
  export interface OutputObject {
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyAcceptedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    insured: AddressLike,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    insured: string,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    insured: string;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCancelledEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyOfferedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    insurer: AddressLike,
    coverageAmount: BigNumberish,
    premiumAmount: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    insurer: string,
    coverageAmount: bigint,
    premiumAmount: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    insurer: string;
    coverageAmount: bigint;
    premiumAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyResolvedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    eventOccurred: boolean,
    payoutToInsured: BigNumberish,
    payoutToInsurer: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    eventOccurred: boolean,
    payoutToInsured: bigint,
    payoutToInsurer: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    eventOccurred: boolean;
    payoutToInsured: bigint;
    payoutToInsurer: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedUpdatedEvent {
  export type InputTuple = [user: AddressLike, verified: boolean];
  export type OutputTuple = [user: string, verified: boolean];
  export interface OutputObject {
    user: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InsuranceEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): InsuranceEscrow;
  waitForDeployment(): Promise<this>;

  interface: InsuranceEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "payable"
  >;

  cancelOffer: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPolicyOffer: TypedContractMethod<
    [
      premiumAmount: BigNumberish,
      durationSeconds: BigNumberish,
      location: string,
      windSpeedKmh: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  finalizeExpiredPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getPolicies: TypedContractMethod<
    [],
    [InsuranceEscrow.PolicyStructOutput[]],
    "view"
  >;

  getPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [InsuranceEscrow.PolicyStructOutput],
    "view"
  >;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        insurer: string;
        insured: string;
        coverageAmount: bigint;
        premiumAmount: bigint;
        durationSeconds: bigint;
        startTime: bigint;
        endTime: bigint;
        location: string;
        windSpeedKmh: bigint;
        state: bigint;
        eventOccurred: boolean;
      }
    ],
    "view"
  >;

  policyCount: TypedContractMethod<[], [bigint], "view">;

  resolvePolicy: TypedContractMethod<
    [policyId: BigNumberish, eventOccurred: boolean],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setVerified: TypedContractMethod<
    [user: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifiedUsers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptPolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelOffer"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPolicyOffer"
  ): TypedContractMethod<
    [
      premiumAmount: BigNumberish,
      durationSeconds: BigNumberish,
      location: string,
      windSpeedKmh: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "finalizeExpiredPolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPolicies"
  ): TypedContractMethod<[], [InsuranceEscrow.PolicyStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [policyId: BigNumberish],
    [InsuranceEscrow.PolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        insurer: string;
        insured: string;
        coverageAmount: bigint;
        premiumAmount: bigint;
        durationSeconds: bigint;
        startTime: bigint;
        endTime: bigint;
        location: string;
        windSpeedKmh: bigint;
        state: bigint;
        eventOccurred: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolvePolicy"
  ): TypedContractMethod<
    [policyId: BigNumberish, eventOccurred: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVerified"
  ): TypedContractMethod<
    [user: AddressLike, verified: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedUsers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyAccepted"
  ): TypedContractEvent<
    PolicyAcceptedEvent.InputTuple,
    PolicyAcceptedEvent.OutputTuple,
    PolicyAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCancelled"
  ): TypedContractEvent<
    PolicyCancelledEvent.InputTuple,
    PolicyCancelledEvent.OutputTuple,
    PolicyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PolicyOffered"
  ): TypedContractEvent<
    PolicyOfferedEvent.InputTuple,
    PolicyOfferedEvent.OutputTuple,
    PolicyOfferedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyResolved"
  ): TypedContractEvent<
    PolicyResolvedEvent.InputTuple,
    PolicyResolvedEvent.OutputTuple,
    PolicyResolvedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedUpdated"
  ): TypedContractEvent<
    VerifiedUpdatedEvent.InputTuple,
    VerifiedUpdatedEvent.OutputTuple,
    VerifiedUpdatedEvent.OutputObject
  >;

  filters: {
    "OracleUpdated(address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyAccepted(uint256,address,uint256,uint256)": TypedContractEvent<
      PolicyAcceptedEvent.InputTuple,
      PolicyAcceptedEvent.OutputTuple,
      PolicyAcceptedEvent.OutputObject
    >;
    PolicyAccepted: TypedContractEvent<
      PolicyAcceptedEvent.InputTuple,
      PolicyAcceptedEvent.OutputTuple,
      PolicyAcceptedEvent.OutputObject
    >;

    "PolicyCancelled(uint256)": TypedContractEvent<
      PolicyCancelledEvent.InputTuple,
      PolicyCancelledEvent.OutputTuple,
      PolicyCancelledEvent.OutputObject
    >;
    PolicyCancelled: TypedContractEvent<
      PolicyCancelledEvent.InputTuple,
      PolicyCancelledEvent.OutputTuple,
      PolicyCancelledEvent.OutputObject
    >;

    "PolicyOffered(uint256,address,uint256,uint256)": TypedContractEvent<
      PolicyOfferedEvent.InputTuple,
      PolicyOfferedEvent.OutputTuple,
      PolicyOfferedEvent.OutputObject
    >;
    PolicyOffered: TypedContractEvent<
      PolicyOfferedEvent.InputTuple,
      PolicyOfferedEvent.OutputTuple,
      PolicyOfferedEvent.OutputObject
    >;

    "PolicyResolved(uint256,bool,uint256,uint256)": TypedContractEvent<
      PolicyResolvedEvent.InputTuple,
      PolicyResolvedEvent.OutputTuple,
      PolicyResolvedEvent.OutputObject
    >;
    PolicyResolved: TypedContractEvent<
      PolicyResolvedEvent.InputTuple,
      PolicyResolvedEvent.OutputTuple,
      PolicyResolvedEvent.OutputObject
    >;

    "VerifiedUpdated(address,bool)": TypedContractEvent<
      VerifiedUpdatedEvent.InputTuple,
      VerifiedUpdatedEvent.OutputTuple,
      VerifiedUpdatedEvent.OutputObject
    >;
    VerifiedUpdated: TypedContractEvent<
      VerifiedUpdatedEvent.InputTuple,
      VerifiedUpdatedEvent.OutputTuple,
      VerifiedUpdatedEvent.OutputObject
    >;
  };
}
