/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace InsuranceEscrow {
  export type WeatherReportStruct = {
    observedAt: BigNumberish;
    rain1h: BigNumberish;
    rain24h: BigNumberish;
    rain72h: BigNumberish;
    consecutiveHeavyRainHours: BigNumberish;
    eventDurationHours: BigNumberish;
    windSpeed: BigNumberish;
    temperature: BigNumberish;
    humidity: BigNumberish;
    weatherCondition: string;
    riskScore: BigNumberish;
  };

  export type WeatherReportStructOutput = [
    observedAt: bigint,
    rain1h: bigint,
    rain24h: bigint,
    rain72h: bigint,
    consecutiveHeavyRainHours: bigint,
    eventDurationHours: bigint,
    windSpeed: bigint,
    temperature: bigint,
    humidity: bigint,
    weatherCondition: string,
    riskScore: bigint
  ] & {
    observedAt: bigint;
    rain1h: bigint;
    rain24h: bigint;
    rain72h: bigint;
    consecutiveHeavyRainHours: bigint;
    eventDurationHours: bigint;
    windSpeed: bigint;
    temperature: bigint;
    humidity: bigint;
    weatherCondition: string;
    riskScore: bigint;
  };

  export type PolicyStruct = {
    user: AddressLike;
    underwriter: AddressLike;
    locationId: string;
    cropType: string;
    thresholdScore: BigNumberish;
    emergencyRain24h: BigNumberish;
    premiumAmount: BigNumberish;
    payoutAmount: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    lastOracleUpdateAt: BigNumberish;
    lastRiskScore: BigNumberish;
    payoutTriggered: boolean;
    state: BigNumberish;
  };

  export type PolicyStructOutput = [
    user: string,
    underwriter: string,
    locationId: string,
    cropType: string,
    thresholdScore: bigint,
    emergencyRain24h: bigint,
    premiumAmount: bigint,
    payoutAmount: bigint,
    startTime: bigint,
    endTime: bigint,
    lastOracleUpdateAt: bigint,
    lastRiskScore: bigint,
    payoutTriggered: boolean,
    state: bigint
  ] & {
    user: string;
    underwriter: string;
    locationId: string;
    cropType: string;
    thresholdScore: bigint;
    emergencyRain24h: bigint;
    premiumAmount: bigint;
    payoutAmount: bigint;
    startTime: bigint;
    endTime: bigint;
    lastOracleUpdateAt: bigint;
    lastRiskScore: bigint;
    payoutTriggered: boolean;
    state: bigint;
  };

  export type QuoteTermsStruct = {
    farmer: AddressLike;
    locationId: string;
    cropType: string;
    thresholdScore: BigNumberish;
    emergencyRain24h: BigNumberish;
    premiumAmount: BigNumberish;
    payoutAmount: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    expiresAt: BigNumberish;
    state: BigNumberish;
  };

  export type QuoteTermsStructOutput = [
    farmer: string,
    locationId: string,
    cropType: string,
    thresholdScore: bigint,
    emergencyRain24h: bigint,
    premiumAmount: bigint,
    payoutAmount: bigint,
    startTime: bigint,
    endTime: bigint,
    expiresAt: bigint,
    state: bigint
  ] & {
    farmer: string;
    locationId: string;
    cropType: string;
    thresholdScore: bigint;
    emergencyRain24h: bigint;
    premiumAmount: bigint;
    payoutAmount: bigint;
    startTime: bigint;
    endTime: bigint;
    expiresAt: bigint;
    state: bigint;
  };
}

export interface InsuranceEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_EMERGENCY_RAIN_24H"
      | "DEFAULT_THRESHOLD_SCORE"
      | "availableLiquidity"
      | "availableUnderwriterCapital"
      | "cancelPolicy"
      | "createPolicy"
      | "createPolicyFromQuote"
      | "expirePolicy"
      | "fundPool"
      | "fundUnderwriterCapital"
      | "getLatestReport"
      | "getPolicies"
      | "getPoliciesByLocation"
      | "getPolicy"
      | "getPremiumLock"
      | "getQuoteLock"
      | "getQuoteTerms"
      | "getUnderwriterCapitalAccount"
      | "lockCapitalForQuote"
      | "lockPremiumForQuote"
      | "lockedReserve"
      | "oracle"
      | "owner"
      | "policies"
      | "policyCount"
      | "registerQuote"
      | "releasePremiumForQuote"
      | "releaseQuoteCapital"
      | "setOracle"
      | "sharedPoolBalance"
      | "sharedPoolLockedReserve"
      | "submitWeatherReport"
      | "transferOwnership"
      | "withdrawUnderwriterCapital"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidityAdded"
      | "OracleUpdated"
      | "OwnershipTransferred"
      | "PolicyCancelled"
      | "PolicyCreated"
      | "PolicyExpired"
      | "PolicyPaidOut"
      | "QuoteCapitalConverted"
      | "QuoteCapitalLocked"
      | "QuoteCapitalReleased"
      | "QuotePremiumConverted"
      | "QuotePremiumLocked"
      | "QuotePremiumReleased"
      | "QuoteRegistered"
      | "QuoteTermsConverted"
      | "UnderwriterCapitalDeposited"
      | "UnderwriterCapitalWithdrawn"
      | "WeatherReportSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_EMERGENCY_RAIN_24H",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_THRESHOLD_SCORE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableUnderwriterCapital",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicy",
    values: [
      AddressLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPolicyFromQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expirePolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "fundPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundUnderwriterCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoliciesByLocation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPremiumLock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteLock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuoteTerms",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnderwriterCapitalAccount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockCapitalForQuote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockPremiumForQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedReserve",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policies",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "policyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerQuote",
    values: [
      BigNumberish,
      AddressLike,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePremiumForQuote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseQuoteCapital",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharedPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharedPoolLockedReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitWeatherReport",
    values: [BigNumberish, InsuranceEscrow.WeatherReportStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnderwriterCapital",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_EMERGENCY_RAIN_24H",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_THRESHOLD_SCORE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableUnderwriterCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPolicyFromQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expirePolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundUnderwriterCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoliciesByLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPremiumLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteLock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuoteTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnderwriterCapitalAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockCapitalForQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockPremiumForQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "policies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePremiumForQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseQuoteCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sharedPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharedPoolLockedReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitWeatherReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnderwriterCapital",
    data: BytesLike
  ): Result;
}

export namespace LiquidityAddedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [
    previousOracle: AddressLike,
    newOracle: AddressLike
  ];
  export type OutputTuple = [previousOracle: string, newOracle: string];
  export interface OutputObject {
    previousOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCancelledEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyCreatedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    user: AddressLike,
    underwriter: AddressLike,
    locationId: string,
    cropType: string,
    thresholdScore: BigNumberish,
    emergencyRain24h: BigNumberish,
    payoutAmount: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    user: string,
    underwriter: string,
    locationId: string,
    cropType: string,
    thresholdScore: bigint,
    emergencyRain24h: bigint,
    payoutAmount: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    user: string;
    underwriter: string;
    locationId: string;
    cropType: string;
    thresholdScore: bigint;
    emergencyRain24h: bigint;
    payoutAmount: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyExpiredEvent {
  export type InputTuple = [policyId: BigNumberish];
  export type OutputTuple = [policyId: bigint];
  export interface OutputObject {
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyPaidOutEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    user: AddressLike,
    underwriter: AddressLike,
    payoutAmount: BigNumberish,
    riskScore: BigNumberish,
    rain24h: BigNumberish
  ];
  export type OutputTuple = [
    policyId: bigint,
    user: string,
    underwriter: string,
    payoutAmount: bigint,
    riskScore: bigint,
    rain24h: bigint
  ];
  export interface OutputObject {
    policyId: bigint;
    user: string;
    underwriter: string;
    payoutAmount: bigint;
    riskScore: bigint;
    rain24h: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteCapitalConvertedEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    policyId: BigNumberish,
    underwriter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: bigint,
    policyId: bigint,
    underwriter: string,
    amount: bigint
  ];
  export interface OutputObject {
    quoteId: bigint;
    policyId: bigint;
    underwriter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteCapitalLockedEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    underwriter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: bigint,
    underwriter: string,
    amount: bigint
  ];
  export interface OutputObject {
    quoteId: bigint;
    underwriter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteCapitalReleasedEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    underwriter: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: bigint,
    underwriter: string,
    amount: bigint
  ];
  export interface OutputObject {
    quoteId: bigint;
    underwriter: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotePremiumConvertedEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    policyId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: bigint,
    policyId: bigint,
    farmer: string,
    amount: bigint
  ];
  export interface OutputObject {
    quoteId: bigint;
    policyId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotePremiumLockedEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [quoteId: bigint, farmer: string, amount: bigint];
  export interface OutputObject {
    quoteId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuotePremiumReleasedEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    farmer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [quoteId: bigint, farmer: string, amount: bigint];
  export interface OutputObject {
    quoteId: bigint;
    farmer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteRegisteredEvent {
  export type InputTuple = [
    quoteId: BigNumberish,
    farmer: AddressLike,
    premiumAmount: BigNumberish,
    payoutAmount: BigNumberish,
    thresholdScore: BigNumberish,
    emergencyRain24h: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    quoteId: bigint,
    farmer: string,
    premiumAmount: bigint,
    payoutAmount: bigint,
    thresholdScore: bigint,
    emergencyRain24h: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    quoteId: bigint;
    farmer: string;
    premiumAmount: bigint;
    payoutAmount: bigint;
    thresholdScore: bigint;
    emergencyRain24h: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuoteTermsConvertedEvent {
  export type InputTuple = [quoteId: BigNumberish, policyId: BigNumberish];
  export type OutputTuple = [quoteId: bigint, policyId: bigint];
  export interface OutputObject {
    quoteId: bigint;
    policyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnderwriterCapitalDepositedEvent {
  export type InputTuple = [
    underwriter: AddressLike,
    amount: BigNumberish,
    totalDeposited: BigNumberish
  ];
  export type OutputTuple = [
    underwriter: string,
    amount: bigint,
    totalDeposited: bigint
  ];
  export interface OutputObject {
    underwriter: string;
    amount: bigint;
    totalDeposited: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnderwriterCapitalWithdrawnEvent {
  export type InputTuple = [
    underwriter: AddressLike,
    amount: BigNumberish,
    remainingDeposited: BigNumberish
  ];
  export type OutputTuple = [
    underwriter: string,
    amount: bigint,
    remainingDeposited: bigint
  ];
  export interface OutputObject {
    underwriter: string;
    amount: bigint;
    remainingDeposited: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WeatherReportSubmittedEvent {
  export type InputTuple = [
    policyId: BigNumberish,
    observedAt: BigNumberish,
    riskScore: BigNumberish,
    rain24h: BigNumberish,
    payoutTriggered: boolean
  ];
  export type OutputTuple = [
    policyId: bigint,
    observedAt: bigint,
    riskScore: bigint,
    rain24h: bigint,
    payoutTriggered: boolean
  ];
  export interface OutputObject {
    policyId: bigint;
    observedAt: bigint;
    riskScore: bigint;
    rain24h: bigint;
    payoutTriggered: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InsuranceEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): InsuranceEscrow;
  waitForDeployment(): Promise<this>;

  interface: InsuranceEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_EMERGENCY_RAIN_24H: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_THRESHOLD_SCORE: TypedContractMethod<[], [bigint], "view">;

  availableLiquidity: TypedContractMethod<[], [bigint], "view">;

  availableUnderwriterCapital: TypedContractMethod<
    [underwriter: AddressLike],
    [bigint],
    "view"
  >;

  cancelPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPolicy: TypedContractMethod<
    [
      user: AddressLike,
      locationId: string,
      cropType: string,
      thresholdScore: BigNumberish,
      emergencyRain24h: BigNumberish,
      payoutAmount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createPolicyFromQuote: TypedContractMethod<
    [quoteId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  expirePolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundPool: TypedContractMethod<[], [void], "payable">;

  fundUnderwriterCapital: TypedContractMethod<[], [void], "payable">;

  getLatestReport: TypedContractMethod<
    [policyId: BigNumberish],
    [InsuranceEscrow.WeatherReportStructOutput],
    "view"
  >;

  getPolicies: TypedContractMethod<
    [],
    [InsuranceEscrow.PolicyStructOutput[]],
    "view"
  >;

  getPoliciesByLocation: TypedContractMethod<
    [locationId: string],
    [bigint[]],
    "view"
  >;

  getPolicy: TypedContractMethod<
    [policyId: BigNumberish],
    [InsuranceEscrow.PolicyStructOutput],
    "view"
  >;

  getPremiumLock: TypedContractMethod<
    [quoteId: BigNumberish],
    [
      [string, bigint, bigint] & {
        farmer: string;
        amount: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getQuoteLock: TypedContractMethod<
    [quoteId: BigNumberish],
    [
      [string, bigint, bigint] & {
        underwriter: string;
        amount: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getQuoteTerms: TypedContractMethod<
    [quoteId: BigNumberish],
    [InsuranceEscrow.QuoteTermsStructOutput],
    "view"
  >;

  getUnderwriterCapitalAccount: TypedContractMethod<
    [underwriter: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        locked: bigint;
        available: bigint;
      }
    ],
    "view"
  >;

  lockCapitalForQuote: TypedContractMethod<
    [quoteId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockPremiumForQuote: TypedContractMethod<
    [quoteId: BigNumberish],
    [void],
    "payable"
  >;

  lockedReserve: TypedContractMethod<[], [bigint], "view">;

  oracle: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  policies: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        user: string;
        underwriter: string;
        locationId: string;
        cropType: string;
        thresholdScore: bigint;
        emergencyRain24h: bigint;
        premiumAmount: bigint;
        payoutAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        lastOracleUpdateAt: bigint;
        lastRiskScore: bigint;
        payoutTriggered: boolean;
        state: bigint;
      }
    ],
    "view"
  >;

  policyCount: TypedContractMethod<[], [bigint], "view">;

  registerQuote: TypedContractMethod<
    [
      quoteId: BigNumberish,
      farmer: AddressLike,
      locationId: string,
      cropType: string,
      thresholdScore: BigNumberish,
      emergencyRain24h: BigNumberish,
      premiumAmount: BigNumberish,
      payoutAmount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  releasePremiumForQuote: TypedContractMethod<
    [quoteId: BigNumberish],
    [void],
    "nonpayable"
  >;

  releaseQuoteCapital: TypedContractMethod<
    [quoteId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOracle: TypedContractMethod<
    [newOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  sharedPoolBalance: TypedContractMethod<[], [bigint], "view">;

  sharedPoolLockedReserve: TypedContractMethod<[], [bigint], "view">;

  submitWeatherReport: TypedContractMethod<
    [policyId: BigNumberish, report: InsuranceEscrow.WeatherReportStruct],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawUnderwriterCapital: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_EMERGENCY_RAIN_24H"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_THRESHOLD_SCORE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableUnderwriterCapital"
  ): TypedContractMethod<[underwriter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelPolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPolicy"
  ): TypedContractMethod<
    [
      user: AddressLike,
      locationId: string,
      cropType: string,
      thresholdScore: BigNumberish,
      emergencyRain24h: BigNumberish,
      payoutAmount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPolicyFromQuote"
  ): TypedContractMethod<[quoteId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "expirePolicy"
  ): TypedContractMethod<[policyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundUnderwriterCapital"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getLatestReport"
  ): TypedContractMethod<
    [policyId: BigNumberish],
    [InsuranceEscrow.WeatherReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPolicies"
  ): TypedContractMethod<[], [InsuranceEscrow.PolicyStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getPoliciesByLocation"
  ): TypedContractMethod<[locationId: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [policyId: BigNumberish],
    [InsuranceEscrow.PolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPremiumLock"
  ): TypedContractMethod<
    [quoteId: BigNumberish],
    [
      [string, bigint, bigint] & {
        farmer: string;
        amount: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuoteLock"
  ): TypedContractMethod<
    [quoteId: BigNumberish],
    [
      [string, bigint, bigint] & {
        underwriter: string;
        amount: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuoteTerms"
  ): TypedContractMethod<
    [quoteId: BigNumberish],
    [InsuranceEscrow.QuoteTermsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUnderwriterCapitalAccount"
  ): TypedContractMethod<
    [underwriter: AddressLike],
    [
      [bigint, bigint, bigint] & {
        deposited: bigint;
        locked: bigint;
        available: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockCapitalForQuote"
  ): TypedContractMethod<
    [quoteId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockPremiumForQuote"
  ): TypedContractMethod<[quoteId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "lockedReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policies"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        user: string;
        underwriter: string;
        locationId: string;
        cropType: string;
        thresholdScore: bigint;
        emergencyRain24h: bigint;
        premiumAmount: bigint;
        payoutAmount: bigint;
        startTime: bigint;
        endTime: bigint;
        lastOracleUpdateAt: bigint;
        lastRiskScore: bigint;
        payoutTriggered: boolean;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "policyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerQuote"
  ): TypedContractMethod<
    [
      quoteId: BigNumberish,
      farmer: AddressLike,
      locationId: string,
      cropType: string,
      thresholdScore: BigNumberish,
      emergencyRain24h: BigNumberish,
      premiumAmount: BigNumberish,
      payoutAmount: BigNumberish,
      startTime: BigNumberish,
      endTime: BigNumberish,
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releasePremiumForQuote"
  ): TypedContractMethod<[quoteId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseQuoteCapital"
  ): TypedContractMethod<[quoteId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[newOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sharedPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sharedPoolLockedReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitWeatherReport"
  ): TypedContractMethod<
    [policyId: BigNumberish, report: InsuranceEscrow.WeatherReportStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUnderwriterCapital"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "LiquidityAdded"
  ): TypedContractEvent<
    LiquidityAddedEvent.InputTuple,
    LiquidityAddedEvent.OutputTuple,
    LiquidityAddedEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCancelled"
  ): TypedContractEvent<
    PolicyCancelledEvent.InputTuple,
    PolicyCancelledEvent.OutputTuple,
    PolicyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PolicyCreated"
  ): TypedContractEvent<
    PolicyCreatedEvent.InputTuple,
    PolicyCreatedEvent.OutputTuple,
    PolicyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyExpired"
  ): TypedContractEvent<
    PolicyExpiredEvent.InputTuple,
    PolicyExpiredEvent.OutputTuple,
    PolicyExpiredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyPaidOut"
  ): TypedContractEvent<
    PolicyPaidOutEvent.InputTuple,
    PolicyPaidOutEvent.OutputTuple,
    PolicyPaidOutEvent.OutputObject
  >;
  getEvent(
    key: "QuoteCapitalConverted"
  ): TypedContractEvent<
    QuoteCapitalConvertedEvent.InputTuple,
    QuoteCapitalConvertedEvent.OutputTuple,
    QuoteCapitalConvertedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteCapitalLocked"
  ): TypedContractEvent<
    QuoteCapitalLockedEvent.InputTuple,
    QuoteCapitalLockedEvent.OutputTuple,
    QuoteCapitalLockedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteCapitalReleased"
  ): TypedContractEvent<
    QuoteCapitalReleasedEvent.InputTuple,
    QuoteCapitalReleasedEvent.OutputTuple,
    QuoteCapitalReleasedEvent.OutputObject
  >;
  getEvent(
    key: "QuotePremiumConverted"
  ): TypedContractEvent<
    QuotePremiumConvertedEvent.InputTuple,
    QuotePremiumConvertedEvent.OutputTuple,
    QuotePremiumConvertedEvent.OutputObject
  >;
  getEvent(
    key: "QuotePremiumLocked"
  ): TypedContractEvent<
    QuotePremiumLockedEvent.InputTuple,
    QuotePremiumLockedEvent.OutputTuple,
    QuotePremiumLockedEvent.OutputObject
  >;
  getEvent(
    key: "QuotePremiumReleased"
  ): TypedContractEvent<
    QuotePremiumReleasedEvent.InputTuple,
    QuotePremiumReleasedEvent.OutputTuple,
    QuotePremiumReleasedEvent.OutputObject
  >;
  getEvent(
    key: "QuoteRegistered"
  ): TypedContractEvent<
    QuoteRegisteredEvent.InputTuple,
    QuoteRegisteredEvent.OutputTuple,
    QuoteRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "QuoteTermsConverted"
  ): TypedContractEvent<
    QuoteTermsConvertedEvent.InputTuple,
    QuoteTermsConvertedEvent.OutputTuple,
    QuoteTermsConvertedEvent.OutputObject
  >;
  getEvent(
    key: "UnderwriterCapitalDeposited"
  ): TypedContractEvent<
    UnderwriterCapitalDepositedEvent.InputTuple,
    UnderwriterCapitalDepositedEvent.OutputTuple,
    UnderwriterCapitalDepositedEvent.OutputObject
  >;
  getEvent(
    key: "UnderwriterCapitalWithdrawn"
  ): TypedContractEvent<
    UnderwriterCapitalWithdrawnEvent.InputTuple,
    UnderwriterCapitalWithdrawnEvent.OutputTuple,
    UnderwriterCapitalWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "WeatherReportSubmitted"
  ): TypedContractEvent<
    WeatherReportSubmittedEvent.InputTuple,
    WeatherReportSubmittedEvent.OutputTuple,
    WeatherReportSubmittedEvent.OutputObject
  >;

  filters: {
    "LiquidityAdded(address,uint256)": TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;
    LiquidityAdded: TypedContractEvent<
      LiquidityAddedEvent.InputTuple,
      LiquidityAddedEvent.OutputTuple,
      LiquidityAddedEvent.OutputObject
    >;

    "OracleUpdated(address,address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PolicyCancelled(uint256)": TypedContractEvent<
      PolicyCancelledEvent.InputTuple,
      PolicyCancelledEvent.OutputTuple,
      PolicyCancelledEvent.OutputObject
    >;
    PolicyCancelled: TypedContractEvent<
      PolicyCancelledEvent.InputTuple,
      PolicyCancelledEvent.OutputTuple,
      PolicyCancelledEvent.OutputObject
    >;

    "PolicyCreated(uint256,address,address,string,string,uint32,uint32,uint256,uint64,uint64)": TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;
    PolicyCreated: TypedContractEvent<
      PolicyCreatedEvent.InputTuple,
      PolicyCreatedEvent.OutputTuple,
      PolicyCreatedEvent.OutputObject
    >;

    "PolicyExpired(uint256)": TypedContractEvent<
      PolicyExpiredEvent.InputTuple,
      PolicyExpiredEvent.OutputTuple,
      PolicyExpiredEvent.OutputObject
    >;
    PolicyExpired: TypedContractEvent<
      PolicyExpiredEvent.InputTuple,
      PolicyExpiredEvent.OutputTuple,
      PolicyExpiredEvent.OutputObject
    >;

    "PolicyPaidOut(uint256,address,address,uint256,uint32,uint32)": TypedContractEvent<
      PolicyPaidOutEvent.InputTuple,
      PolicyPaidOutEvent.OutputTuple,
      PolicyPaidOutEvent.OutputObject
    >;
    PolicyPaidOut: TypedContractEvent<
      PolicyPaidOutEvent.InputTuple,
      PolicyPaidOutEvent.OutputTuple,
      PolicyPaidOutEvent.OutputObject
    >;

    "QuoteCapitalConverted(uint256,uint256,address,uint256)": TypedContractEvent<
      QuoteCapitalConvertedEvent.InputTuple,
      QuoteCapitalConvertedEvent.OutputTuple,
      QuoteCapitalConvertedEvent.OutputObject
    >;
    QuoteCapitalConverted: TypedContractEvent<
      QuoteCapitalConvertedEvent.InputTuple,
      QuoteCapitalConvertedEvent.OutputTuple,
      QuoteCapitalConvertedEvent.OutputObject
    >;

    "QuoteCapitalLocked(uint256,address,uint256)": TypedContractEvent<
      QuoteCapitalLockedEvent.InputTuple,
      QuoteCapitalLockedEvent.OutputTuple,
      QuoteCapitalLockedEvent.OutputObject
    >;
    QuoteCapitalLocked: TypedContractEvent<
      QuoteCapitalLockedEvent.InputTuple,
      QuoteCapitalLockedEvent.OutputTuple,
      QuoteCapitalLockedEvent.OutputObject
    >;

    "QuoteCapitalReleased(uint256,address,uint256)": TypedContractEvent<
      QuoteCapitalReleasedEvent.InputTuple,
      QuoteCapitalReleasedEvent.OutputTuple,
      QuoteCapitalReleasedEvent.OutputObject
    >;
    QuoteCapitalReleased: TypedContractEvent<
      QuoteCapitalReleasedEvent.InputTuple,
      QuoteCapitalReleasedEvent.OutputTuple,
      QuoteCapitalReleasedEvent.OutputObject
    >;

    "QuotePremiumConverted(uint256,uint256,address,uint256)": TypedContractEvent<
      QuotePremiumConvertedEvent.InputTuple,
      QuotePremiumConvertedEvent.OutputTuple,
      QuotePremiumConvertedEvent.OutputObject
    >;
    QuotePremiumConverted: TypedContractEvent<
      QuotePremiumConvertedEvent.InputTuple,
      QuotePremiumConvertedEvent.OutputTuple,
      QuotePremiumConvertedEvent.OutputObject
    >;

    "QuotePremiumLocked(uint256,address,uint256)": TypedContractEvent<
      QuotePremiumLockedEvent.InputTuple,
      QuotePremiumLockedEvent.OutputTuple,
      QuotePremiumLockedEvent.OutputObject
    >;
    QuotePremiumLocked: TypedContractEvent<
      QuotePremiumLockedEvent.InputTuple,
      QuotePremiumLockedEvent.OutputTuple,
      QuotePremiumLockedEvent.OutputObject
    >;

    "QuotePremiumReleased(uint256,address,uint256)": TypedContractEvent<
      QuotePremiumReleasedEvent.InputTuple,
      QuotePremiumReleasedEvent.OutputTuple,
      QuotePremiumReleasedEvent.OutputObject
    >;
    QuotePremiumReleased: TypedContractEvent<
      QuotePremiumReleasedEvent.InputTuple,
      QuotePremiumReleasedEvent.OutputTuple,
      QuotePremiumReleasedEvent.OutputObject
    >;

    "QuoteRegistered(uint256,address,uint256,uint256,uint32,uint32,uint64)": TypedContractEvent<
      QuoteRegisteredEvent.InputTuple,
      QuoteRegisteredEvent.OutputTuple,
      QuoteRegisteredEvent.OutputObject
    >;
    QuoteRegistered: TypedContractEvent<
      QuoteRegisteredEvent.InputTuple,
      QuoteRegisteredEvent.OutputTuple,
      QuoteRegisteredEvent.OutputObject
    >;

    "QuoteTermsConverted(uint256,uint256)": TypedContractEvent<
      QuoteTermsConvertedEvent.InputTuple,
      QuoteTermsConvertedEvent.OutputTuple,
      QuoteTermsConvertedEvent.OutputObject
    >;
    QuoteTermsConverted: TypedContractEvent<
      QuoteTermsConvertedEvent.InputTuple,
      QuoteTermsConvertedEvent.OutputTuple,
      QuoteTermsConvertedEvent.OutputObject
    >;

    "UnderwriterCapitalDeposited(address,uint256,uint256)": TypedContractEvent<
      UnderwriterCapitalDepositedEvent.InputTuple,
      UnderwriterCapitalDepositedEvent.OutputTuple,
      UnderwriterCapitalDepositedEvent.OutputObject
    >;
    UnderwriterCapitalDeposited: TypedContractEvent<
      UnderwriterCapitalDepositedEvent.InputTuple,
      UnderwriterCapitalDepositedEvent.OutputTuple,
      UnderwriterCapitalDepositedEvent.OutputObject
    >;

    "UnderwriterCapitalWithdrawn(address,uint256,uint256)": TypedContractEvent<
      UnderwriterCapitalWithdrawnEvent.InputTuple,
      UnderwriterCapitalWithdrawnEvent.OutputTuple,
      UnderwriterCapitalWithdrawnEvent.OutputObject
    >;
    UnderwriterCapitalWithdrawn: TypedContractEvent<
      UnderwriterCapitalWithdrawnEvent.InputTuple,
      UnderwriterCapitalWithdrawnEvent.OutputTuple,
      UnderwriterCapitalWithdrawnEvent.OutputObject
    >;

    "WeatherReportSubmitted(uint256,uint64,uint32,uint32,bool)": TypedContractEvent<
      WeatherReportSubmittedEvent.InputTuple,
      WeatherReportSubmittedEvent.OutputTuple,
      WeatherReportSubmittedEvent.OutputObject
    >;
    WeatherReportSubmitted: TypedContractEvent<
      WeatherReportSubmittedEvent.InputTuple,
      WeatherReportSubmittedEvent.OutputTuple,
      WeatherReportSubmittedEvent.OutputObject
    >;
  };
}
